language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install:
  - composer install
script: phpunit --verbose --coverage-text --coverage-clover=/tmp/ahutils/coverage.clover
after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover /tmp/ahutils/coverage.clover; fi
